
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Nov 11 20:42:02 IST 2016
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface TokenNames {
  /* terminals */
  public static final int MINUS = 3;
  public static final int DIVIDE = 5;
  public static final int NUMBER = 9;
  public static final int EOF = 0;
  public static final int PLUS = 2;
  public static final int ID = 10;
  public static final int error = 1;
  public static final int SEMICOLON = 8;
  public static final int RPAREN = 7;
  public static final int TIMES = 4;
  public static final int LPAREN = 6;
}

