
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class TokenNames {
  /* terminals */
  public static final int TIMES = 6;
  public static final int RBRACK = 12;
  public static final int SEMICOLON = 15;
  public static final int PLUS = 4;
  public static final int INT = 17;
  public static final int RBRACE = 14;
  public static final int RPAREN = 10;
  public static final int WHILE = 7;
  public static final int LBRACK = 11;
  public static final int IF = 2;
  public static final int LPAREN = 9;
  public static final int LBRACE = 13;
  public static final int ID = 18;
  public static final int EOF = 0;
  public static final int DIVIDE = 8;
  public static final int MINUS = 5;
  public static final int error = 1;
  public static final int DOT = 3;
  public static final int ASSIGN = 16;
  public static final int UMINUS = 19;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IF",
  "DOT",
  "PLUS",
  "MINUS",
  "TIMES",
  "WHILE",
  "DIVIDE",
  "LPAREN",
  "RPAREN",
  "LBRACK",
  "RBRACK",
  "LBRACE",
  "RBRACE",
  "SEMICOLON",
  "ASSIGN",
  "INT",
  "ID",
  "UMINUS"
  };
}

