.PHONY example_01:
example_01:
	@./make_example_01
.PHONY example_01_elf:
example_01_elf:
	@./make_example_01_elf
.PHONY example_02:
example_02:
	@./make_example_02
.PHONY example_02_elf:
example_02_elf:
	@./make_example_02_elf
.PHONY example_03:
example_03: make_example_03
	@./make_example_03
.PHONY example_04:
example_04: make_example_04
	@./make_example_04
.PHONY example_05:
example_05: make_example_05
	@./make_example_05
.PHONY example_06:
example_06: make_example_06
	@./make_example_06
