#!/bin/bash
resize -s 32 78
clear
setterm -term linux -fore blue
echo -e "\033[1m\$ cat example_03.c\033[0m"
setterm -term linux -fore white
cat example_03.c
setterm -term linux -fore blue
echo -e "\033[1m\$ clang -c -emit-llvm example_03.c\033[0m"
setterm -term linux -fore white
clang -c -emit-llvm example_03.c
setterm -term linux -fore blue
echo -e "\033[1m\$ opt -instnamer -o example_03.bc example_03.bc\033[0m"
setterm -term linux -fore white
opt -instnamer -o example_03.bc example_03.bc
setterm -term linux -fore blue
echo -e "\033[1m\$ llvm-dis example_03.bc\033[0m"
setterm -term linux -fore white
llvm-dis example_03.bc
setterm -term linux -fore blue
echo -e "\033[1m\$ sed -n '8,20p;21q' example_03.ll\033[0m"
setterm -term linux -fore white
sed -n '8,20p;21q' example_03.ll
gnome-screenshot -w -f ./example_03.png
cp ./example_03.png ../LATEX/example_03.png
