#!/bin/bash
resize -s 40 75
clear
setterm -term linux -fore blue
echo -e "\033[1m\$ clang -g -O0 -o example_01 example_01.c\033[0m"
setterm -term linux -fore white
clang -g -O0 -o example_01 example_01.c
setterm -term linux -fore blue
echo -e "\033[1m\$ objdump -S example_01 | cat -n | sed -n '100,123p;124q'\033[0m"
setterm -term linux -fore white
objdump -S example_01 | cat -n | sed -n '100,123p;124q'
gnome-screenshot -w -f ./example_01_elf.png
cp ./example_01_elf.png ../LATEX/example_01_elf.png
