#!/bin/bash
resize -s 37 65
clear
setterm -term linux -fore blue
echo -e "\033[1m\$ cat example_05.c\033[0m"
setterm -term linux -fore white
cat example_05.c
setterm -term linux -fore blue
echo -e "\033[1m\$ clang -c -emit-llvm example_05.c\033[0m"
setterm -term linux -fore white
clang -c -emit-llvm example_05.c
setterm -term linux -fore blue
echo -e "\033[1m\$ opt -instnamer -o example_05.bc example_05.bc\033[0m"
setterm -term linux -fore white
opt -instnamer -o example_05.bc example_05.bc
setterm -term linux -fore blue
echo -e "\033[1m\$ llvm-dis example_05.bc\033[0m"
setterm -term linux -fore white
llvm-dis example_05.bc
setterm -term linux -fore blue
echo -e "\033[1m\$ sed -i -e 's/\s\{3,\}; preds/    ; preds/g' example_05.ll\033[0m"
setterm -term linux -fore white
sed -i -e 's/\s\{3,\}; preds/    ; preds/g' example_05.ll
setterm -term linux -fore blue
echo -e "\033[1m\$ sed -n '25,42p;43q' example_05.ll\033[0m"
setterm -term linux -fore white
sed -n '25,42p;43q' example_05.ll
gnome-screenshot -w -f ./example_05.png
cp ./example_05.png ../LATEX/example_05.png
