#!/bin/bash
resize -s 41 115
clear
setterm -term linux -fore blue
echo -e "\033[1m\$ cat example_06.cpp\033[0m"
setterm -term linux -fore white
cat example_06.cpp
setterm -term linux -fore blue
echo -e "\033[1m\$ clang -c -emit-llvm example_06.cpp\033[0m"
setterm -term linux -fore white
clang -c -emit-llvm example_06.cpp
setterm -term linux -fore blue
echo -e "\033[1m\$ opt -instnamer -o example_06.bc example_06.bc\033[0m"
setterm -term linux -fore white
opt -instnamer -o example_06.bc example_06.bc
setterm -term linux -fore blue
echo -e "\033[1m\$ llvm-dis example_06.bc\033[0m"
setterm -term linux -fore white
llvm-dis example_06.bc
setterm -term linux -fore blue
echo -e "\033[1m\$ sed -i -e 's/\s\{3,\}; preds/    ; preds/g' example_06.ll\033[0m"
setterm -term linux -fore white
sed -i -e 's/\s\{3,\}; preds/    ; preds/g' example_06.ll
setterm -term linux -fore blue
echo -e "\033[1m\$ sed -n '10,23p;24q' example_06.ll\033[0m"
setterm -term linux -fore white
sed -n '10,23p;24q' example_06.ll
gnome-screenshot -w -f ./example_06.png
cp ./example_06.png ../LATEX/example_06.png
