#!/bin/bash
resize -s 40 65
clear
setterm -term linux -fore blue
echo -e "\033[1m\$ cat example_04.c\033[0m"
setterm -term linux -fore white
cat example_04.c
setterm -term linux -fore blue
echo -e "\033[1m\$ clang -c -emit-llvm example_04.c\033[0m"
setterm -term linux -fore white
clang -c -emit-llvm example_04.c
setterm -term linux -fore blue
echo -e "\033[1m\$ opt -instnamer -o example_04.bc example_04.bc\033[0m"
setterm -term linux -fore white
opt -instnamer -o example_04.bc example_04.bc
setterm -term linux -fore blue
echo -e "\033[1m\$ llvm-dis example_04.bc\033[0m"
setterm -term linux -fore white
llvm-dis example_04.bc
setterm -term linux -fore blue
echo -e "\033[1m\$ sed -i -e 's/\s\{3,\}; preds/    ; preds/g' example_04.ll\033[0m"
setterm -term linux -fore white
sed -i -e 's/\s\{3,\}; preds/    ; preds/g' example_04.ll
setterm -term linux -fore blue
echo -e "\033[1m\$ sed -n '14,34p;35q' example_04.ll\033[0m"
setterm -term linux -fore white
sed -n '14,34p;35q' example_04.ll
gnome-screenshot -w -f ./example_04.png
cp ./example_04.png ../LATEX/example_04.png
