#!/bin/bash
resize -s 41 70
clear
setterm -term linux -fore blue
echo -e "\033[1m\$ cat example_03.cs\033[0m"
setterm -term linux -fore white
cat example_03.cs
setterm -term linux -fore blue
echo -e "\033[1m\$ mcs -debug example_03.cs\033[0m"
setterm -term linux -fore white
mcs -debug example_03.cs
setterm -term linux -fore blue
echo -e "\033[1m\$ monodis example_03.exe > example_03.cil\033[0m"
setterm -term linux -fore white
monodis example_03.exe > example_03.cil
setterm -term linux -fore blue
echo -e "\033[1m\$ sed -n '67,83p;84q' example_03.cil\033[0m"
setterm -term linux -fore white
sed -n '67,83p;84q' example_03.cil
gnome-screenshot -w -f ./example_03.png
cp ./example_03.png ../LATEX/example_03.png
