#!/bin/bash
resize -s 41 60
clear
setterm -term linux -fore blue
echo -e "\033[1m\$ cat example_02.c\033[0m"
setterm -term linux -fore white
cat example_02.c
setterm -term linux -fore blue
echo -e "\033[1m\$ rm *.gimple && gcc -O0 -c -fdump-tree-all example_02.c\033[0m"
setterm -term linux -fore white
rm *.gimple && gcc -O0 -c -fdump-tree-all example_02.c
setterm -term linux -fore blue
echo -e "\033[1m\$ cp *.gimple example_02.gimple && rm example_02.c.*\033[0m"
setterm -term linux -fore white
cp *.gimple example_02.gimple && rm example_02.c.*
setterm -term linux -fore blue
echo -e "\033[1m\$ sed -n '1,22p;23q' example_02.gimple\033[0m"
setterm -term linux -fore white
sed -n '1,22p;23q' example_02.gimple
gnome-screenshot -w -f ./example_02.png
cp ./example_02.png ../LATEX/example_02.png
