#!/bin/bash
resize -s 35 85
clear
setterm -term linux -fore blue
echo -e "\033[1m\$ cat example_04.java\033[0m"
setterm -term linux -fore white
cat example_04.java
setterm -term linux -fore blue
echo -e "\033[1m\$ javac example_04.java\033[0m"
setterm -term linux -fore white
javac example_04.java
setterm -term linux -fore blue
echo -e "\033[1m\$ javap -l -c example_04.class > example_04.bytecode\033[0m"
setterm -term linux -fore white
javap -l -c example_04.class > example_04.bytecode
setterm -term linux -fore blue
echo -e "\033[1m\$ sed -n '11,23p;24q' example_04.bytecode\033[0m"
setterm -term linux -fore white
sed -n '11,23p;24q' example_04.bytecode
gnome-screenshot -w -f ./example_04.png
cp ./example_04.png ../LATEX/example_04.png
