.PHONY: example_01
example_01:
	@clear
	@setterm -term linux -fore blue
	@echo "************************"
	@echo "*                      *"
	@echo "* [0] Compile with gcc *"
	@echo "*                      *"
	@echo "************************"
	@setterm -term linux -fore white
	gcc -o example_01_gcc example_01_chuck_norris_changing_a_const_value.c
	@setterm -term linux -fore blue
	@echo "**************************"
	@echo "*                        *"
	@echo "* [1] Compile with clang *"
	@echo "*                        *"
	@echo "**************************"
	@setterm -term linux -fore white
	clang -o example_01_clang example_01_chuck_norris_changing_a_const_value.c
	@setterm -term linux -fore blue
	@echo "********************************"
	@echo "*                              *"
	@echo "* [2] Run gcc compiled version *"
	@echo "*                              *"
	@echo "********************************"
	@setterm -term linux -fore white
	./example_01_gcc
	@setterm -term linux -fore blue
	@echo "**********************************"
	@echo "*                                *"
	@echo "* [3] Run clang compiled version *"
	@echo "*                                *"
	@echo "**********************************"
	@setterm -term linux -fore white
	./example_01_clang

.PHONY: example_02
example_02:
	@clear
	@setterm -term linux -fore blue
	@echo "************************"
	@echo "*                      *"
	@echo "* [0] Compile with gcc *"
	@echo "*                      *"
	@echo "************************"
	@setterm -term linux -fore white
	gcc -o example_02_gcc   example_02_chuck_norris_changing_a_const_string.c
	@setterm -term linux -fore blue
	@echo "**************************"
	@echo "*                        *"
	@echo "* [1] Compile with clang *"
	@echo "*                        *"
	@echo "**************************"
	@setterm -term linux -fore white
	clang -o example_02_clang example_02_chuck_norris_changing_a_const_string.c
	@setterm -term linux -fore blue
	@echo "********************************"
	@echo "*                              *"
	@echo "* [2] Run gcc compiled version *"
	@echo "*                              *"
	@echo "********************************"
	@setterm -term linux -fore white
	./example_02_gcc
	@setterm -term linux -fore blue
	@echo "**********************************"
	@echo "*                                *"
	@echo "* [3] Run clang compiled version *"
	@echo "*                                *"
	@echo "**********************************"
	@setterm -term linux -fore white
	./example_02_clang

.PHONY: example_03
example_03:
	@clear
	@setterm -term linux -fore blue
	@echo "************************"
	@echo "*                      *"
	@echo "* [0] Compile with gcc *"
	@echo "*                      *"
	@echo "************************"
	@setterm -term linux -fore white
	gcc -o example_03_gcc example_03_string_pooling.c
	@setterm -term linux -fore blue
	@echo "**************************"
	@echo "*                        *"
	@echo "* [1] Compile with clang *"
	@echo "*                        *"
	@echo "**************************"
	@setterm -term linux -fore white
	clang -o example_03_clang example_03_string_pooling.c
	@setterm -term linux -fore blue
	@echo "********************************"
	@echo "*                              *"
	@echo "* [2] Run gcc compiled version *"
	@echo "*                              *"
	@echo "********************************"
	@setterm -term linux -fore white
	./example_03_gcc
	@setterm -term linux -fore blue
	@echo "**********************************"
	@echo "*                                *"
	@echo "* [3] Run clang compiled version *"
	@echo "*                                *"
	@echo "**********************************"
	@setterm -term linux -fore white
	./example_03_clang

.PHONY: example_04
example_04:
	@clear
	@setterm -term linux -fore blue
	@echo "************************"
	@echo "*                      *"
	@echo "* [0] Compile with gcc *"
	@echo "*                      *"
	@echo "************************"
	@setterm -term linux -fore white
	gcc -o example_04_gcc example_04_destructing_objects.cpp
	@setterm -term linux -fore blue
	@echo "**************************"
	@echo "*                        *"
	@echo "* [1] Compile with clang *"
	@echo "*                        *"
	@echo "**************************"
	@setterm -term linux -fore white
	clang -o example_04_clang example_04_destructing_objects.cpp
	@setterm -term linux -fore blue
	@echo "********************************"
	@echo "*                              *"
	@echo "* [2] Run gcc compiled version *"
	@echo "*                              *"
	@echo "********************************"
	@setterm -term linux -fore white
	./example_04_gcc
	@setterm -term linux -fore blue
	@echo "**********************************"
	@echo "*                                *"
	@echo "* [3] Run clang compiled version *"
	@echo "*                                *"
	@echo "**********************************"
	@setterm -term linux -fore white
	./example_04_clang

