#! /bin/bash
echo ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
echo +"                                                                                      "+
echo +"                                                                                      "+
echo + [0] Clean *.class files and machine generated Lexer.java Parser.java TokenNames.java +
echo +"                                                                                      "+
echo +"                                                                                      "+
echo ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
echo rm -rf FOLDER_2_SRC/Lexer.java FOLDER_2_SRC/Parser.java FOLDER_2_SRC/TokenNames.java FOLDER_3_BIN/*.class FOLDER_3_BIN/AST/*.class
     rm -rf FOLDER_2_SRC/Lexer.java FOLDER_2_SRC/Parser.java FOLDER_2_SRC/TokenNames.java FOLDER_3_BIN/*.class FOLDER_3_BIN/AST/*.class
echo ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
echo +"                                                          "+
echo +"                                                          "+
echo + [1] Use JFlex to synthesize Lexer.java from LEX_FILE.lex +
echo +"                                                          "+
echo +"                                                          "+
echo ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
echo jflex -q -d FOLDER_2_SRC FOLDER_0_JFlex/LEX_FILE.lex
     jflex -q -d FOLDER_2_SRC FOLDER_0_JFlex/LEX_FILE.lex
echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
echo +"                                                                             "+
echo +"                                                                             "+
echo + [2] Use CUP to synthesize Parser.java and TokenNames.java from CUP_FILE.cup +
echo +"                                                                             "+
echo +"                                                                             "+
echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
echo java -jar ./FOLDER_7_EXTERNAL_JARS/java-cup-11b.jar -nowarn -destdir ./FOLDER_2_SRC -parser Parser -symbols TokenNames ./FOLDER_1_CUP/CUP_FILE.cup
     java -jar ./FOLDER_7_EXTERNAL_JARS/java-cup-11b.jar -nowarn -destdir ./FOLDER_2_SRC -parser Parser -symbols TokenNames ./FOLDER_1_CUP/CUP_FILE.cup
echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++
echo +"                                                       "+
echo +"                                                       "+
echo +  [3] Create *.class files from *.java files + CUP JAR +
echo +"                                                       "+
echo +"                                                       "+
echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++
echo javac -cp ./FOLDER_7_EXTERNAL_JARS/java-cup-11b-runtime.jar -d ./FOLDER_3_BIN FOLDER_2_SRC/*.java FOLDER_2_SRC/AST/*.java
     javac -cp ./FOLDER_7_EXTERNAL_JARS/java-cup-11b-runtime.jar -d ./FOLDER_3_BIN FOLDER_2_SRC/*.java FOLDER_2_SRC/AST/*.java
echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
echo +"                                                         "+
echo +"                                                         "+
echo + [4] Create a JAR file from from *.class files + CUP JAR +
echo +"                                                         "+
echo +"                                                         "+
echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
echo jar cfm PARSER.jar ./FOLDER_8_MANIFEST/MANIFEST.MF -C ./FOLDER_3_BIN/ .
     jar cfm PARSER.jar ./FOLDER_8_MANIFEST/MANIFEST.MF -C ./FOLDER_3_BIN/ .
echo +++++++++++++++++++++++++++++
echo +"                           "+
echo +"                           "+
echo + [5] Run resulting program +
echo +"                           "+
echo +"                           "+
echo +++++++++++++++++++++++++++++
echo java -jar PARSER.jar ./FOLDER_4_INPUT/Input.txt ./FOLDER_5_OUTPUT/ParseStatus.txt
     java -jar PARSER.jar ./FOLDER_4_INPUT/Input.txt ./FOLDER_5_OUTPUT/ParseStatus.txt

